In [30]:
import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [31]:
latest_movies = pd.read_csv(
    r"C:\Dev\projects\movie_recommendation_agent\data\processed\latest_movies_clean.csv"
)

latest_movies.head(2)

,title,overview,release_date,vote_average,popularity,release_year
0,Our Fault,Jenna and Lion's wedding brings about the long...,2025-10-15,7.869,1096.6654,2025.0
1,Inside Furioza,"In the wake of murder, new Furioza leader Gold...",2025-10-14,6.593,384.3220,2025.0

In [ ]:
latest_movies["combined_text"] = (
    latest_movies["title"].fillna("") + " " +
    latest_movies["overview"].fillna("")
) #made comibed text of title and overview

In [ ]:
latest_movies["combined_text"].iloc[0] #onlt print first position text

In [ ]:
model = SentenceTransformer(
    "all-MiniLM-L6-v2"
) #384 dimensional vector

In [ ]:
sample_embeddings = model.encode(
    latest_movies["combined_text"].head(5).tolist()
)

In [ ]:
sample_embeddings.shape

In [ ]:
movie_embeddings = model.encode(
    latest_movies["combined_text"].tolist(),
    show_progress_bar=True
)

In [ ]:
import joblib

joblib.dump(
    movie_embeddings,
    r"C:\Dev\projects\movie_recommendation_agent\data\embeddings\movie_embeddings.pkl"
)

In [ ]:
movie_embeddings = joblib.load(
    r"C:\Dev\projects\movie_recommendation_agent\data\embeddings\movie_embeddings.pkl",
)

In [ ]:
similarity_matrix = cosine_similarity(
    movie_embeddings
)

In [ ]:
movie_embeddings[:2] #tp see output
movie_embed_df = pd.DataFrame(movie_embeddings)
movie_embed_df.iloc[0]

In [ ]:
similarity_matrix.shape

In [ ]:
import joblib

joblib.dump(
    similarity_matrix,
    r"C:\Dev\projects\movie_recommendation_agent\data\embeddings\similarity_matrix.pkl"
)

In [ ]:
similarity_matrix = joblib.load(
    r"C:\Dev\projects\movie_recommendation_agent\data\embeddings\similarity_matrix.pkl"
)

In [ ]:
similarity_matrix[:3]

In [ ]:
movie_index = pd.Series(
    latest_movies.index, 
    index=latest_movies["title"]
).drop_duplicates() 
#create a index with movie title like map Interstellar -> 7

In [ ]:
movie_index["Interstellar"] # Testing and got index value

In [ ]:
movie_index_test = movie_index["Interstellar"]
similarity_scores_test = similarity_matrix[movie_index_test]
#Listing out similar movies

In [ ]:
similarity_scores_test[:10] #10 similar movie

In [ ]:
similar_movies_test = list(
    enumerate(similarity_scores_test)
) #list movies with index + similarity

In [ ]:
sorted_movies_test = sorted(
    similar_movies_test,
    key= lambda x: x[1],
    reverse=True
) #highest similarity first

In [ ]:
sorted_movies_test[:10] # need to skip self similarity

In [ ]:
top10_movies = sorted_movies_test[1:11]

In [ ]:
for movie in top10_movies:
    movie_index = movie[0]

    print(
        latest_movies.iloc[movie_index]["title"]
    )

In [ ]:
latest_movies["title"].duplicated().sum()
#there is more duplicate in current table

In [34]:
latest_movies[latest_movies["title"].duplicated()].head(5)
#view duplicate feature

,title,overview,release_date,vote_average,popularity,release_year
23,KPop Demon Hunters,"When K-pop superstars Rumi, Mira and Zoey aren...",2025-06-20,8.300,145.3272,2025.0
89,Gypsy Moon,The year is 1799 Romania. The Gypsy people on ...,2024-02-14,7.000,38.5500,2024.0
102,The Roses,Life seems easy for picture-perfect couple Ivy...,2025-08-27,7.077,35.3951,2025.0
109,Harry Potter and the Philosopher's Stone,Harry Potter has lived under the stairs at his...,2001-11-16,7.900,34.5961,2001.0
122,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,8.713,34.5159,1994.0

In [35]:
latest_movies = latest_movies.drop_duplicates(
    subset="title"
)

In [36]:
latest_movies = latest_movies.reset_index(
    drop=True
)

In [37]:
latest_movies["title"].duplicated().sum() # No duplicate

np.int64(0)

In [38]:
latest_movies.shape

(7397, 6)

In [39]:
latest_movies["combined_text"] = (
    latest_movies["title"].fillna("") + " "
    + latest_movies["overview"].fillna("")
)

In [41]:
import joblib

movie_embeddings = joblib.load(
    r"C:\Dev\projects\movie_recommendation_agent\data\embeddings\movie_embeddings.pkl"
)

similarity_matrix = joblib.load(
    r"C:\Dev\projects\movie_recommendation_agent\data\embeddings\similarity_matrix.pkl"
)

In [ ]:
movie_embeddings = model.encode(
    latest_movies["combined_text"].tolist(),
    show_progress_bar=True
)

In [ ]:
similarity_matrix = cosine_similarity(
    movie_embeddings
)

In [42]:
movie_indices = pd.Series(
    latest_movies.index,
    index=latest_movies["title"]
).drop_duplicates()

In [ ]:
import joblib

joblib.dump(
    movie_embeddings,
    r"C:\Dev\projects\movie_recommendation_agent\data\embeddings\movie_embeddings.pkl"
)

joblib.dump(
    similarity_matrix,
    r"C:\Dev\projects\movie_recommendation_agent\data\embeddings\similarity_matrix.pkl"
)

In [ ]:
# movie_index = movie_indices["Interstellar"]
movie_index = movie_indices["Titanic"]

similarity_scores = similarity_matrix[movie_index]

similar_movies = list(enumerate(similarity_scores))

sorted_movies = sorted(
    similar_movies,
    key=lambda x: x[1],
    reverse=True
)

top_movies = sorted_movies[1:11]

for movie in top_movies:
    print(
        latest_movies.iloc[movie[0]]["title"]
    )

In [43]:
print(movie_index)
latest_movies.iloc[movie_indices["Interstellar"]]["title"]

153

'Interstellar'

In [44]:
latest_movies.iloc[movie_indices["Interstellar"]]["overview"]

'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.'

In [46]:
movie_idx = movie_indices["Interstellar"]

latest_movies.iloc[movie_idx][
    ["title", "overview"]
]

title                                            Interstellar
overview    The adventures of a group of explorers who mak...
Name: 47, dtype: object

In [47]:
movie_idx = movie_indices["Interstellar"]

scores = list(
    enumerate(similarity_matrix[movie_idx])
)

scores = sorted(
    scores,
    key=lambda x: x[1],
    reverse=True
)

scores[:10]

[(47, np.float32(1.0000001)),
 (671, np.float32(0.52626467)),
 (2012, np.float32(0.4605941)),
 (1646, np.float32(0.45744908)),
 (1489, np.float32(0.44674218)),
 (1116, np.float32(0.43114698)),
 (1206, np.float32(0.43044147)),
 (3319, np.float32(0.42656147)),
 (6839, np.float32(0.41897887)),
 (6283, np.float32(0.41878462))]

In [48]:
movie_idx = movie_indices["Interstellar"]

scores = list(
    enumerate(similarity_matrix[movie_idx])
)

scores = sorted(
    scores,
    key=lambda x: x[1],
    reverse=True
)

for idx, score in scores[1:11]:

    print(
        latest_movies.iloc[idx]["title"],
        " --> ",
        round(score, 3)
    )

Prometheus  -->  0.526
Stargate  -->  0.461
Lost in Starlight  -->  0.457
Atlantis: The Lost Empire  -->  0.447
Treasure Planet  -->  0.431
As Above, So Below  -->  0.43
Mickey's Explorers  -->  0.427
Journey to the Seventh Planet  -->  0.419
Extraterrestrial  -->  0.419
Space: The Longest Goodbye  -->  0.413

In [52]:
print(latest_movies.shape)
print(similarity_matrix.shape)

(7397, 7)
(7397, 7397)

In [53]:
latest_movies.columns

Index(['title', 'overview', 'release_date', 'vote_average', 'popularity',
       'release_year', 'combined_text'],
      dtype='str')

In [55]:
latest_movies.to_csv(
    "../data/processed/latest_movies_final.csv",
    index=False
)